import GlobalState from "@/context";
import { Inter } from "next/font/google";
import "../globals.css";
import LayoutClient from "./layout.client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <LayoutClient>{children}</LayoutClient>
        </GlobalState>
      </body>
    </html>
  );
}
