"use client";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";
import GlobalState from "@/context";
import { useAuth } from "@/hooks/auth";
import { Inter } from "next/font/google";
import { useState } from "react";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  const { user } = useAuth({ middleware: "auth" });
  const [selectedMenuItem, setSelectedMenuItem] = useState("Dashboard");
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <div className="flex h-screen overflow-hidden">
            <Sidebar setSelectedMenuItem={setSelectedMenuItem} />
            <div className="relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden">
              <Header title={selectedMenuItem} user={user} />
              <main>
                <div className="p-7 md:p-6 2xl:p-10">{children}</div>
              </main>
            </div>
          </div>
        </GlobalState>
      </body>
    </html>
  );
}
